use crate::types::*;

/// Signal generated by strategy.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Signal {
    Enter(ContractType),
    Exit,
    Hold,
}

// ── Multi-Timeframe Candle ──────────────────────────────────────────

/// A completed OHLC candle.
#[derive(Debug, Clone, Copy)]
struct Candle {
    open: f64,
    high: f64,
    low: f64,
    close: f64,
}

/// Aggregates raw ticks into fixed-count candles (each candle = N ticks).
struct CandleAggregator {
    /// Number of ticks per candle
    ticks_per_candle: usize,
    /// Buffer accumulating ticks for the current forming candle
    current_open: f64,
    current_high: f64,
    current_low: f64,
    current_close: f64,
    tick_count: usize,
    /// Completed candles (ring buffer, max 500)
    candles: Vec<Candle>,
}

impl CandleAggregator {
    fn new(ticks_per_candle: usize) -> Self {
        Self {
            ticks_per_candle,
            current_open: 0.0,
            current_high: f64::MIN,
            current_low: f64::MAX,
            current_close: 0.0,
            tick_count: 0,
            candles: Vec::new(),
        }
    }

    /// Feed a tick; returns true if a new candle was completed.
    fn push(&mut self, price: f64) -> bool {
        if self.tick_count == 0 {
            self.current_open = price;
            self.current_high = price;
            self.current_low = price;
        }
        if price > self.current_high {
            self.current_high = price;
        }
        if price < self.current_low {
            self.current_low = price;
        }
        self.current_close = price;
        self.tick_count += 1;

        if self.tick_count >= self.ticks_per_candle {
            self.candles.push(Candle {
                open: self.current_open,
                high: self.current_high,
                low: self.current_low,
                close: self.current_close,
            });
            if self.candles.len() > 500 {
                self.candles.drain(..250);
            }
            self.tick_count = 0;
            self.current_high = f64::MIN;
            self.current_low = f64::MAX;
            true
        } else {
            false
        }
    }

    fn len(&self) -> usize {
        self.candles.len()
    }

    /// Return the last N close prices.
    fn closes(&self, n: usize) -> Vec<f64> {
        let start = self.candles.len().saturating_sub(n);
        self.candles[start..].iter().map(|c| c.close).collect()
    }

    /// Return the last N candles.
    fn last_n(&self, n: usize) -> &[Candle] {
        let start = self.candles.len().saturating_sub(n);
        &self.candles[start..]
    }
}

// ── Indicator helpers (operate on slices) ───────────────────────────

fn ema_slice(data: &[f64], period: usize) -> f64 {
    if data.is_empty() {
        return 0.0;
    }
    let k = 2.0 / (period as f64 + 1.0);
    let mut ema = data[0];
    for &val in data.iter().skip(1) {
        ema = val * k + ema * (1.0 - k);
    }
    ema
}

fn rsi_from_closes(closes: &[f64], period: usize) -> Option<f64> {
    if closes.len() < period + 1 {
        return None;
    }
    let slice = &closes[closes.len() - period - 1..];
    let mut gains = 0.0;
    let mut losses = 0.0;
    for i in 1..=period {
        let d = slice[i] - slice[i - 1];
        if d > 0.0 {
            gains += d;
        } else {
            losses += d.abs();
        }
    }
    let avg_gain = gains / period as f64;
    let avg_loss = losses / period as f64;
    let rs = if avg_loss > 0.0 {
        avg_gain / avg_loss
    } else {
        100.0
    };
    Some(100.0 - 100.0 / (1.0 + rs))
}

fn bb_position(closes: &[f64], period: usize, num_std: f64) -> Option<f64> {
    if closes.len() < period {
        return None;
    }
    let slice = &closes[closes.len() - period..];
    let mean: f64 = slice.iter().sum::<f64>() / period as f64;
    let variance: f64 = slice.iter().map(|p| (p - mean).powi(2)).sum::<f64>() / period as f64;
    let std = variance.sqrt();
    if std < 1e-12 {
        return None;
    }
    let last = *closes.last().unwrap();
    // Return normalized position: < -1 = below lower band, > +1 = above upper band
    Some((last - mean) / (num_std * std))
}

/// Average True Range from candles.
fn atr_from_candles(candles: &[Candle], period: usize) -> Option<f64> {
    if candles.len() < period + 1 {
        return None;
    }
    let slice = &candles[candles.len() - period - 1..];
    let mut sum_tr = 0.0;
    for i in 1..slice.len() {
        let tr = (slice[i].high - slice[i].low)
            .max((slice[i].high - slice[i - 1].close).abs())
            .max((slice[i].low - slice[i - 1].close).abs());
        sum_tr += tr;
    }
    Some(sum_tr / period as f64)
}

// ── Direction vote ──────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq)]
enum Regime {
    Bullish,
    Bearish,
    Neutral,
}

#[derive(Debug, Clone, Copy)]
enum Direction {
    Up,
    Down,
    Neutral,
}

impl Direction {
    fn score(self) -> i32 {
        match self {
            Direction::Up => 1,
            Direction::Down => -1,
            Direction::Neutral => 0,
        }
    }
}

// ── Strategy Engine ─────────────────────────────────────────────────

/// Momentum Confluence strategy with Multi-Timeframe analysis.
///
/// Timeframes (tick-based):
///   - Fast:  5 ticks/candle  (~10 seconds on R_100)
///   - Mid:  15 ticks/candle  (~30 seconds)
///   - Slow: 30 ticks/candle  (~60 seconds)
///
/// Indicators per timeframe:
///   - EMA fast(20) / slow(50) → trend direction
///   - RSI(30) → momentum extremes
///
/// Global filters:
///   - BB(100, 2.5σ) on raw ticks → breakout detection
///   - ATR volatility filter on mid candles → skip low-vol regimes
///   - Alpha edge ≥ 8% → model confidence
///
/// Entry rule: 3+ confirmations from different sources, all same direction.
pub struct StrategyEngine {
    pub strategy_type: StrategyType,
    prices: Vec<f64>,

    // Multi-timeframe candle aggregators
    tf_fast: CandleAggregator, //  5 ticks/candle (~10s)
    tf_mid: CandleAggregator,  // 15 ticks/candle (~30s)
    tf_slow: CandleAggregator, // 30 ticks/candle (~60s)
}

impl StrategyEngine {
    pub fn new(strategy_type: StrategyType) -> Self {
        Self {
            strategy_type,
            prices: Vec::new(),
            tf_fast: CandleAggregator::new(5),
            tf_mid: CandleAggregator::new(15),
            tf_slow: CandleAggregator::new(30),
        }
    }

    /// Feed a new price tick.
    pub fn on_tick(&mut self, price: f64) {
        self.prices.push(price);
        if self.prices.len() > 5000 {
            self.prices.drain(..1000);
        }

        // Aggregate into MTF candles
        self.tf_fast.push(price);
        self.tf_mid.push(price);
        self.tf_slow.push(price);
    }

    /// Generate signal based on alpha output and strategy.
    pub fn generate_signal(
        &mut self,
        alpha: &AlphaOutput,
        _risk: &RiskDecision,
        time_left_sec: f64,
    ) -> Signal {
        if time_left_sec < 10.0 {
            return Signal::Hold;
        }

        match self.strategy_type {
            StrategyType::Temporal => self.temporal_signal(alpha, time_left_sec),
            StrategyType::Rsi => self.legacy_rsi_signal(),
            StrategyType::BollingerBands => self.legacy_bb_signal(),
            StrategyType::Macd => self.legacy_macd_signal(),
            StrategyType::Ensemble => self.momentum_confluence_signal(alpha, time_left_sec),
            _ => self.temporal_signal(alpha, time_left_sec),
        }
    }

    fn momentum_confluence_signal(&self, alpha: &AlphaOutput, time_left_sec: f64) -> Signal {
        // Need minimum data: at least 60 slow candles = 1800 ticks (~60 min warmup)
        if self.tf_slow.len() < 60 || self.tf_mid.len() < 60 || self.tf_fast.len() < 60 {
            if self.prices.len() % 50 == 0 {
                tracing::info!(
                    warmup_slow = self.tf_slow.len(),
                    warmup_mid = self.tf_mid.len(),
                    warmup_fast = self.tf_fast.len(),
                    required = 60,
                    "Strategy Engine Warming Up (Gathering Candles)..."
                );
            }
            return Signal::Hold;
        }

        let slow_closes = self.tf_slow.closes(60);
        let mid_closes = self.tf_mid.closes(60);
        let fast_closes = self.tf_fast.closes(60);

        // ── 1. Detect Regime (Macro Context) ────────────────────────
        let mut regime = Regime::Neutral;

        let ema_slow_now = ema_slice(&slow_closes, 20);
        let older = &slow_closes[..slow_closes.len().saturating_sub(10)];
        let ema_slow_prev = ema_slice(older, 20);
        let slow_slope = ema_slow_now - ema_slow_prev;

        let ema_mid_now = ema_slice(&mid_closes, 15);

        if slow_slope > 0.05 && ema_mid_now > ema_slow_now {
            regime = Regime::Bullish;
        } else if slow_slope < -0.05 && ema_mid_now < ema_slow_now {
            regime = Regime::Bearish;
        }

        // ── 2. Volatility Filter (Always active) ────────────────────
        let mid_candles = self.tf_mid.last_n(30);
        let mut atr_pct_val = 0.0;
        if let Some(atr) = atr_from_candles(mid_candles, 14) {
            let last_price = self.prices.last().copied().unwrap_or(1.0);
            let atr_pct = atr / last_price;
            atr_pct_val = atr_pct;
            if atr_pct < 0.0002 {
                if self.prices.len() % 10 == 0 {
                    tracing::debug!("HOLD: Dead market (ATR: {:.6})", atr_pct);
                }
                return Signal::Hold; // Market is dead
            }
        }

        // ── 3. Alpha Edge Filter (Model Confirmation) ───────────────
        let edge = alpha.q_final.0 - 0.5;
        // Reduced threshold from 0.05/0.07 to 0.02/0.03 to allow trades in normal volatility
        let edge_threshold = if time_left_sec > 120.0 { 0.03 } else { 0.02 };
        let alpha_dir = if edge.abs() >= edge_threshold {
            Some(if edge > 0.0 {
                Direction::Up
            } else {
                Direction::Down
            })
        } else {
            None
        };

        // ── 4. Regime-Specific Micro Execution ──────────────────────
        let mut final_sig = Signal::Hold;
        let mut setup_name = "";

        match regime {
            Regime::Bullish => {
                // Bullish: Dip Buying
                let ema_fast_now = ema_slice(&fast_closes, 10);
                let ema_fast_prev =
                    ema_slice(&fast_closes[..fast_closes.len().saturating_sub(5)], 10);
                let fast_slope = ema_fast_now - ema_fast_prev;

                let rsi = rsi_from_closes(&fast_closes, 14);
                let bb_pos = bb_position(&self.prices, 100, 2.5);

                // Entry triggers: Fast EMA slope turns positive AND (RSI < 45 OR hits lower BB)
                let rsi_bull = matches!(rsi, Some(r) if r < 45.0);
                let bb_bull = matches!(bb_pos, Some(p) if p < -0.8);
                if fast_slope > 0.03 && (rsi_bull || bb_bull) {
                    if matches!(alpha_dir, Some(Direction::Up)) {
                        final_sig = Signal::Enter(ContractType::Call);
                        setup_name = "Bullish_DipBuy";
                    }
                }
            }
            Regime::Bearish => {
                // Bearish: Rally Selling
                let ema_fast_now = ema_slice(&fast_closes, 10);
                let ema_fast_prev =
                    ema_slice(&fast_closes[..fast_closes.len().saturating_sub(5)], 10);
                let fast_slope = ema_fast_now - ema_fast_prev;

                let rsi = rsi_from_closes(&fast_closes, 14);
                let bb_pos = bb_position(&self.prices, 100, 2.5);

                // Entry triggers: Fast EMA slope turns strongly negative AND (RSI spikes > 55 OR significantly breaks upper BB)
                let rsi_bear = matches!(rsi, Some(r) if r > 55.0);
                let bb_bear = matches!(bb_pos, Some(p) if p > 1.0);
                if fast_slope < -0.05 && (rsi_bear || bb_bear) {
                    if matches!(alpha_dir, Some(Direction::Down)) {
                        final_sig = Signal::Enter(ContractType::Put);
                        setup_name = "Bearish_RallySell";
                    }
                }
            }
            Regime::Neutral => {
                // Neutral: Mean Reversion / Range Trading
                let rsi = rsi_from_closes(&mid_closes, 30);
                let bb_pos = bb_position(&self.prices, 100, 2.5);

                // Demand confluence of RSI extremes + BB boundaries
                if matches!(rsi, Some(r) if r < 35.0) && matches!(bb_pos, Some(p) if p < -1.0) {
                    if matches!(alpha_dir, Some(Direction::Up)) {
                        final_sig = Signal::Enter(ContractType::Call);
                        setup_name = "Neutral_RangeCall";
                    }
                } else if matches!(rsi, Some(r) if r > 65.0) && matches!(bb_pos, Some(p) if p > 1.0)
                {
                    if matches!(alpha_dir, Some(Direction::Down)) {
                        final_sig = Signal::Enter(ContractType::Put);
                        setup_name = "Neutral_RangePut";
                    }
                }
            }
        }

        if self.prices.len() % 10 == 0 {
            tracing::info!(
                regime = ?regime,
                slow_slope = slow_slope,
                edge = edge,
                atr_pct = atr_pct_val,
                "Strategy State"
            );
        }

        // Live strategy evaluation is side-effect free.
        // Dataset recording, if reintroduced later, should live behind an explicit offline recorder interface.

        if final_sig != Signal::Hold {
            tracing::info!(regime = ?regime, setup = setup_name, final_sig = ?final_sig, "Regime Adaptive Setup Triggered");
        }

        final_sig
    }

    // ── Legacy strategies (kept for backward compat) ─────────────────

    fn temporal_signal(&self, alpha: &AlphaOutput, time_left_sec: f64) -> Signal {
        let edge_up = alpha.q_final.0 - 0.5;
        let edge_threshold = if time_left_sec > 60.0 { 0.05 } else { 0.03 };
        if edge_up.abs() < edge_threshold {
            return Signal::Hold;
        }
        if edge_up > 0.0 {
            Signal::Enter(ContractType::Call)
        } else {
            Signal::Enter(ContractType::Put)
        }
    }

    fn legacy_rsi_signal(&self) -> Signal {
        if self.prices.len() < 15 {
            return Signal::Hold;
        }
        match rsi_from_closes(&self.prices, 14) {
            Some(rsi) if rsi < 30.0 => Signal::Enter(ContractType::Call),
            Some(rsi) if rsi > 70.0 => Signal::Enter(ContractType::Put),
            _ => Signal::Hold,
        }
    }

    fn legacy_bb_signal(&self) -> Signal {
        match bb_position(&self.prices, 20, 2.0) {
            Some(pos) if pos < -1.0 => Signal::Enter(ContractType::Call),
            Some(pos) if pos > 1.0 => Signal::Enter(ContractType::Put),
            _ => Signal::Hold,
        }
    }

    fn legacy_macd_signal(&self) -> Signal {
        if self.prices.len() < 35 {
            return Signal::Hold;
        }
        let ema12 = ema_slice(&self.prices, 12);
        let ema26 = ema_slice(&self.prices, 26);
        let macd = ema12 - ema26;
        let mut macd_line = Vec::new();
        for i in 26..self.prices.len() {
            let e12 = ema_slice(&self.prices[..=i], 12);
            let e26 = ema_slice(&self.prices[..=i], 26);
            macd_line.push(e12 - e26);
        }
        if macd_line.len() < 9 {
            return Signal::Hold;
        }
        let signal_line = ema_slice(&macd_line, 9);
        if macd > signal_line && macd > 0.0 {
            Signal::Enter(ContractType::Call)
        } else if macd < signal_line && macd < 0.0 {
            Signal::Enter(ContractType::Put)
        } else {
            Signal::Hold
        }
    }

    /// Evaluate current market regime for logging.
    pub fn evaluate_regime(&self, time_left_sec: f64) -> &'static str {
        if time_left_sec > 120.0 {
            "EARLY"
        } else if time_left_sec > 30.0 {
            "MID"
        } else {
            "LATE"
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{AlphaOutput, Prob, RiskDecision, StrategyType, Usd};

    #[test]
    fn test_generate_signal_does_not_write_dataset_file() {
        let dir = tempfile::tempdir().unwrap();
        let old = std::env::current_dir().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();

        let mut engine = StrategyEngine::new(StrategyType::Temporal);
        for i in 0..120 {
            engine.on_tick(100.0 + (i as f64 * 0.01));
        }
        let alpha = AlphaOutput {
            q_model: Prob(0.62),
            q_mkt: Prob(0.62),
            q_final: Prob(0.62),
            q_low: Prob(0.60),
            q_high: Prob(0.64),
            confidence: 0.55,
        };
        let risk = RiskDecision {
            fraction: 0.01,
            max_size: Usd(1.0),
        };
        let _ = engine.generate_signal(&alpha, &risk, 120.0);

        assert!(!dir.path().join("dataset_v7.csv").exists());
        std::env::set_current_dir(old).unwrap();
    }
}
